spring.application.name=Silolink
spring.datasource.url=jdbc:mysql://localhost:3306/silolink?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true


spring.datasource.username=root
spring.datasource.password=230307

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081